---
- name: Calling the role to install postgresql   
  hosts: dev 
  gather_facts: yes
  become: true
  become_user: root
  vars_files: 
    - ./db_users_dev.yml
    - ./databases.yml
  roles: 
    - postgresql-role 
