---
- name: Calling the role to install postgresql   
  hosts: dev 
  gather_facts: yes
  become: true
  become_user: root
  vars_file: 
   - ./db_users_prod.yml
   - ./databases.yml
  roles: 
    - postgresql-role 
